version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 20000:20000
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80/tcp
