version: "3"
services:
  web:
    build:
      context: ./docker/construct_web # Dockerfile保存場所
      dockerfile: Dockerfile # Dockerfileファイル名
    image: nn-web # docker image name
    container_name: nn-web # docker container name
    ports:
      - 23456:23456

  app:
    build:
      context: ./
      dockerfile: ./docker/construct_app/Dockerfile # Dockerfileファイル名
    image: nn-app # イメージ名
    container_name: nn-app # コンテナ名
    ports: # ポート接続
      - 20000:20000
