version: "3"
services:
  nodejs_server:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile

  nginx:
    build: ./docker/nginx/
    ports:
      - 5580:80
      - 5443:443
    links:
      - nodejs_server:nodejs_server
