version: "3"
services:
  web:
    build: ./docker/nginx/
    image: nn-web
    container_name: nn-web
    ports:
      - 5080:80
      - 5043:443
    links:
      - app:app

  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    image: nn-app
    container_name: nn-app
